# Generated by Django 2.2.6 on 2019-10-30 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Dep Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Depp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Department', verbose_name='Departman')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaxOffice', models.CharField(max_length=100, verbose_name='Vergi Dairesi')),
                ('TaxNumber', models.CharField(max_length=11, verbose_name='Vergi Numarası')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('tax_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='company.Tax')),
                ('full_name', models.CharField(max_length=200, verbose_name='Şirketin Tam Adı')),
                ('short_name', models.CharField(max_length=50, verbose_name='Şirketin Kısaltımı')),
                ('bagla', models.ManyToManyField(to='company.Department', verbose_name='Dep Seçiniz')),
            ],
            bases=('company.tax',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('depp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='company.Depp')),
                ('staff_name', models.CharField(max_length=100, verbose_name='Çalışan Adı')),
                ('staff_rank', models.CharField(choices=[('stj', 'Stajyer'), ('jun', 'junior'), ('sen', 'Senior')], max_length=20, verbose_name='Rank')),
                ('staff_pay', models.PositiveIntegerField(default=10)),
                ('contact_person', models.BooleanField(default=False)),
                ('bagla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            bases=('company.depp',),
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(choices=[('rea', 'React'), ('pyt', 'Python'), ('ren', 'React Native')], max_length=100, verbose_name='Yeteneği')),
                ('seviyesi', models.CharField(choices=[('blg', 'Başlangıç'), ('ort', 'Orta'), ('uz', 'Uzman')], max_length=100)),
                ('bagla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Staff')),
            ],
        ),
    ]
